server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bartender
    password: 191243
    username: postgres
  jpa:
    database: postgresql
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          charset_name: UTF-8
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
          import_files: bartender.sql


